### ISSUE TITLE
"Official" Racket docset

### ISSUE THREAD

**Issue by Kapeli** [Ephemera/racket-docset-generator#1]
Hi @Ephemera. This is just a heads-up that a Racket docset made by me will be released in the next Dash update. Please let me know what you would like to happen with your Racket docset in the user contributed section? Should I remove it or will you continue to support it alongside my own docset? Either way is fine with me.

If you want to check out my own docset, you can grab it from http://kapeli.com/feeds/Racket.tgz. Let me know if you have any comments or notice anything wrong.

**Comment by Ephemera** [comment]
@Kapeli 
I'm fine even if you remove it.

Have you plan to add icons?

**Comment by Kapeli** [comment]
Yes, icons will work after the update is released.

**Comment by Ephemera** [comment]
Good. Thanks for Official Racket docset.
